apiVersion: gateway.kyma-project.io/v1alpha1
kind: APIRule
metadata:
  name: get-order
spec:
  gateway: kyma-gateway.kyma-system.svc.cluster.local
  rules:
    - path: /.*
      accessStrategies:
        - config: {}
          handler: noop
      methods:
        - GET # allow GET requests
  service:
    host: get-order # map them to this host on port 80
    name: get-order
    port: 80
